### ISSUE TITLE
Not Suppoted For Xcode 7.1

### ISSUE THREAD

**Issue by wjxforu** [FuzzyAutocomplete/FuzzyAutocompletePlugin#100]
Well, I updated my Xcode to 7.1 yesterday. And i'm really regret about this, cause i can not use Fuzzy any more.

**Comment by leszarna** [comment]
You need probably to reinstall Alcatraz and then reinstall Fuzzy. It works with 7.1 for sure.

**Comment by slazyk** [comment]
Correct, it does. You just need to install a newer version.

**Comment by wjxforu** [comment]
OK,thanx. I try it ,and it works now. Sorry for the bother

2015-10-28 4:53 GMT+08:00 leszarna <notifications@github.com>:
