### ISSUE TITLE
Does not work with Xcode 7.1.1 (7B1005)

### ISSUE THREAD

**Issue by ngothanhtai** [FuzzyAutocomplete/FuzzyAutocompletePlugin#105]
Hi,
After downloading FuzzyAutocomplete.xcplugin, add it to ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/
-> No "FuzzyAutocomplete" in Editor menu

I also had problem of installing Alcatrax. 
-> No "Package Manager" in Window menu

I am using OS X El Capitan, Xcode 7.1.1 (7B1005)

Cheers,
Tai

**Comment by ngothanhtai** [comment]
I just reinstalled Alcatraz and it works. Just crash for first time install FuzzyAutocomplete but try it later, it works fine.

**Comment by Judy-u** [comment]
yes i agree
