### ISSUE TITLE
Just a hint

### ISSUE THREAD

**Issue by charlieMonroe** [FuzzyAutocomplete/FuzzyAutocompletePlugin#111]
Hi,

it's a great plugin, just wanted to let you know that there already is something like this implemented in Xcode itself. It's in the Debug menu, which needs to be enabled via a 3rd party application or command line (it's a defaults option). See attached image. Perhaps you could use that somehow.

![screen shot 2015-12-09 at 6 37 05 pm](https://cloud.githubusercontent.com/assets/64899/11693225/f252760c-9ea3-11e5-886d-2888d41411d5.png)

**Comment by ngothanhtai** [comment]
Hi @charlieMonroe,
Which 3rd party application you are using to show this Menu.

**Comment by charlieMonroe** [comment]
Can't find the app anymore, but looking into the preferences file, this command will do:

```
defaults write "com.apple.dt.Xcode" "ShowDVTDebugMenu" -bool true
```

**Comment by slazyk** [comment]
Thanks. Yes, I have been aware of this being available through different default keys at least since 7.0.
