### ISSUE TITLE
couldn't parse contents of '/Users/Liki/....../FuzzyAutocomplete-Info.plist'，路径下找不到这个plist文件

### ISSUE THREAD

**Issue by quxingzhe** [FuzzyAutocomplete/FuzzyAutocompletePlugin#113]
我在运行插件的时候，xcode报错。错误内容是不能解析plist文件，然后我去这个目录找，发现没有这文件；请问， 这个问题我要怎么破？

error log:
error: couldn't parse contents of '/Users/Liki/Documents/devutil/plugin/FuzzyAutocompletePlugin/FuzzyAutocomplete/FuzzyAutocomplete-Info.plist': The data couldn’t be read because it isn’t in the correct format.

**Comment by 7934345** [comment]
你尝试 删除plugin 之后重新安装(或者重新编译)
