### ISSUE TITLE
missing completions

### ISSUE THREAD

**Issue by pvinis** [FuzzyAutocomplete/FuzzyAutocompletePlugin#116]
this happens often. this is one example.
i have `snapDirsAndDists` as a variable.
i try to complete with `snapdsss` and it doesnt complete. `snapdss` is ok though.
why is it that the last `s` cannot be found?

**Comment by slazyk** [comment]
My guess would be that it just does not make it above the scoring threshold.
By default the plugin does not show all completions, just the ones with high enough scores.
You should be able to tweak it to your liking in settings.
