### ISSUE TITLE
只要退格删除就会Xcode崩溃

### ISSUE THREAD

**Issue by laowenlu** [FuzzyAutocomplete/FuzzyAutocompletePlugin#117]
Xcode崩溃报错： UNCAUGHT EXCEPTION (NSRangeException): NSMutableRLEArray objectAtIndex:effectiveRange:runIndex:: Out of bounds

Xcode版本7.1

**Comment by Huang-Libo** [comment]
@laowenlu  use English to describe...

**Comment by tomrlq** [comment]
I do not know why you submit a issue in Chinese. I think you can update to Xcode 8

**Comment by Huang-Libo** [comment]
xcode8's built-in Autocomplete works very well.Suggest you update.

**Comment by 7934345** [comment]
what @laowenlu said is

Xcode crashed, when he typed the backspace key.

and his Xcode version is 7.1

**Comment by slazyk** [comment]
I believe this is obsolete at this point.
