### ISSUE TITLE
Build fail 4 XCode 7.3

### ISSUE THREAD

**Issue by TryToBeAExcellentCoder** [FuzzyAutocomplete/FuzzyAutocompletePlugin#118]

**Comment by TryToBeAExcellentCoder** [comment]
I upgraded Xcode to Ver 7.3 today, when I install this plugin, it was built fail.. 
Is anything wrong in my process?

**Comment by jxdwinter** [comment]
+1.some to me.

**Comment by ppbdrinker** [comment]
Installing via alcatraz seems to have no effect either.

**Comment by keepyounger** [comment]
#114 maybe help.

**Comment by jxdwinter** [comment]
@ppbdrinker Thanks! Alcatraz works!

**Comment by zekunyan** [comment]
I had this error: Symbol not found: _OBJC_CLASS_$_DVTTextCompletionInlinePreviewController

**Comment by erikolofsson** [comment]
You can find a rough fix here that simply ignores the functions that are now unavailable in Xcode 7.3:
https://github.com/erikolofsson/FuzzyAutocompletePlugin/commit/b927567e8b4c26ecb6c9278449f31851bdd537be

I'm sure there are many bugs, but from initial testing core features seems to work. The updated Xcode headers are probably useful to figure out anything else that needs doing.

**Comment by KenmuHuang** [comment]
I had this error: Symbol not found: OBJC_CLASS$_DVTTextCompletionInlinePreviewController
Xcode 7.3 can't use it. 
How to solve this issue?

**Comment by fjswhl** [comment]
Install through Alcatraz not work too, actually the installation is failed but alcatrac hadn't prompt you. You can see from Editor menu that there is no 'FuzzyCompletion' submenu under it

**Comment by gerald-coddut** [comment]
what @fjswhl says; alcatraz shows that it is 'installed' but it is never shown in XCode's menubar...

**Comment by 7934345** [comment]
Any update schedule yet?

**Comment by yangyu2010** [comment]
some to me. What's the matter?

**Comment by chen0807130004** [comment]
Can you fixed this plugin error when used in xcode7.3。 when used xcode 7.3  @import or #import  we need to build again,fuck of the xcode7.3 new.we need you,we need your plugin.

**Comment by XiFengLang** [comment]
+1,some to me.

**Comment by longbow007** [comment]
Same to me, the error is:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DVTTextCompletionInlinePreviewController", referenced from:
      l_OBJC_$_CATEGORY_DVTTextCompletionInlinePreviewController_$_FuzzyAutocomplete in DVTTextCompletionInlinePreviewController+FuzzyAutocomplete.o

Please fix Fuzzy for us, we need you! Xcode 7.3 auto completion sucks...

**Comment by Rdxer** [comment]
'''
Same to me, the error is:
Undefined symbols for architecture x86_64:
"OBJC_CLASS$DVTTextCompletionInlinePreviewController", referenced from:
l_OBJC$CATEGORY_DVTTextCompletionInlinePreviewController$_FuzzyAutocomplete in DVTTextCompletionInlinePreviewController+FuzzyAutocomplete.o

Please fix Fuzzy for us, we need you! Xcode 7.3 auto completion sucks...
'''

+1

**Comment by slazyk** [comment]
I wasn't expecting much demand for it, given builtin fuzzy autocompletion in Xcode 7.3. Is there actually any interest in version for Xcode 7.3+?

I haven't actually used Xcode 7.3 much... Can anyone tell me what are the problems with builtin fuzzy autocompletion?

**Comment by guoranliaoran** [comment]
I had this error:
Undefined symbols for architecture x86_64:
"OBJC_CLASS$DVTTextCompletionInlinePreviewController", referenced from:
l_OBJC$CATEGORY_DVTTextCompletionInlinePreviewController$_FuzzyAutocomplete in DVTTextCompletionInlinePreviewController+FuzzyAutocomplete.o

Please fix Fuzzy for us, we need you! Xcode 7.3 auto completion sucks...

**Comment by lanmaoxinqing** [comment]
@slazyk  The problem with built in fuzzy autocompletion is, when I want to type a variable with autocompletion, it doesn't work even after I have imported the header file.  Only after I rebuild the project, it works.

**Comment by guoranliaoran** [comment]
@lanmaoxinqing  Hi,you can have a try like this: In your Project -> TARGETS -> Build Settings -> Weak References in Manual Retain Release  and set Debug = YES, it worked for me.

**Comment by Menq** [comment]
some to me , any schedule to fix this!  It seems a long time no update!!!

**Comment by yaokaige** [comment]
XCode7.3.1 beta released, seems they have fixed code complete issue.

**Comment by KenmuHuang** [comment]
@yaokaige Are you sure Xcode 7.3.1 beta have fixed code complete issue?

**Comment by Menq** [comment]
@KenmuHuang 
I try 7.3.1 , nothing seems different.  if any progress , tell me.

**Comment by yaokaige** [comment]
@KenmuHuang yes, the build in autocomplete bug is gone, and now has the same experience like this plugin

**Comment by KenmuHuang** [comment]
@yaokaige I will try to install Xcode 7.3.1 beta later. Thank you for notice.

**Comment by junjielu** [comment]
Xcode 7.3.1 still cannot install this plugin.I have try all the way to install this plugin.However,via Alcatraz,the plugin seems to be zero bytes.And when I try to build the latest project,2 errors occured which is 

> Undefined symbols for architecture x86_64:
"OBJC_CLASS$DVTTextCompletionInlinePreviewController", referenced from:
l_OBJC$CATEGORY_DVTTextCompletionInlinePreviewController$_FuzzyAutocomplete in DVTTextCompletionInlinePreviewController+FuzzyAutocomplete.o

Please fix this bug,this is a good plugin!

**Comment by danieleforlani** [comment]
same problem here, I would like to have this working because it was more reliable than apple auto completion!

**Comment by tomrlq** [comment]
For those who complain about the build in auto-completion, I recommend you to update to Xcode 8. Since Xcode 8 has fixed all the bugs, you can use the build in fuzzy auto-completion
