### ISSUE TITLE
Xcode 7.3 升级后无法使用该插件 / FuzzyAutocompletePlugin without effect

### ISSUE THREAD

**Issue by ChristXie** [FuzzyAutocomplete/FuzzyAutocompletePlugin#122]

**Comment by ChristXie** [comment]
按照作者的提示修改了UUID可惜并没有什么用，有没有人可以帮助我解决？

**Comment by ChristXie** [comment]
已经解决了，可以去https://github.com/erikolofsson/FuzzyAutocompletePlugin下载，亲测有效!
I fix it ! you can download https://github.com/erikolofsson/FuzzyAutocompletePlugin  , it's work!

**Comment by slazyk** [comment]
Xcode 7.3 has fuzzy autocompletion built in and enabled by default without any plugins.

The two implementations do differ in some details so I am figuring out if and how to proceed.
