### ISSUE TITLE
Uninstall plugin, but it still work. Xcode7.3

### ISSUE THREAD

**Issue by RangeChiong** [FuzzyAutocomplete/FuzzyAutocompletePlugin#123]
I update my xcode to 7.3 . I don't want to use it now. So I uninstall it. Restart xcode, it still work~~!! Again and again.

**Comment by lmorit** [comment]
You do know that xcode 7.3 has its own autocomplete feature right?

**Comment by fjswhl** [comment]
Actually this plugin didn't work in Xcode 7.3 at all :(

**Comment by dev4dev** [comment]
@fjswhl but built-in solution works quite well
