### ISSUE TITLE
 "_OBJC_CLASS_$_DVTTextCompletionInlinePreviewController", referenced from:pen 

### ISSUE THREAD

**Issue by ChinaKingKong** [FuzzyAutocomplete/FuzzyAutocompletePlugin#126]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DVTTextCompletionInlinePreviewController", referenced from:
      l_OBJC_$_CATEGORY_DVTTextCompletionInlinePreviewController_$_FuzzyAutocomplete in DVTTextCompletionInlinePreviewController+FuzzyAutocomplete.o
      objc-class-ref in FuzzyAutocomplete.o
ld: symbol(s) not found for architecture x86_64

**Comment by mrhyh** [comment]
我遇到的也是这个问题.

**Comment by songxing10000** [comment]
the same problem,why

**Comment by ferologics** [comment]
same issue when trying to `carthage update` with AwesomeCache, fails the build
