### ISSUE TITLE
[Enhancement] Add option to not show "No Completions" message

### ISSUE THREAD

**Issue by krackers** [FuzzyAutocomplete/FuzzyAutocompletePlugin#55]
When writing new functions fuzzy autocomplete still tries to find completions for method names and when it can't it pops up a message saying "No Completions" that gets in the way of what you are trying to write. Perhaps it would be better to follow the xcode default of not showing any message if there are no autocomplete options available.

**Comment by ooopscc** [comment]
+1 for this feature, if there are no completions, you should only dismiss the dialog and show nothing.

**Comment by slazyk** [comment]
Agreed, should be consistent with default Xcode behaviour.
