### ISSUE TITLE
10.10.2 pre-release version Xcode issue.

### ISSUE THREAD

**Issue by jxdwinter** [FuzzyAutocomplete/FuzzyAutocompletePlugin#56]
![screen shot 2015-01-08 at 09 52 24](https://cloud.githubusercontent.com/assets/1195524/5656739/4a916dd6-971c-11e4-8fb5-c3ec86f6741d.png)

**Comment by rmvz3** [comment]
Same here

**Comment by slazyk** [comment]
This should be fixed by #57, please verify

**Comment by rmvz3** [comment]
I downloaded the zip file, build it and everything went OK. Just a few minutes before, Alcatraz version didn't worked. Thanks

**Comment by lexrus** [comment]
#57 works in 10.10.2(14C94b).

**Comment by CavalcanteLeo** [comment]
cant open my xcode anymore... I will remove this plugin

**Comment by slazyk** [comment]
@CavalcanteLeo This should have already been resolved at the time you commented. Have you tried upgrading/reinstalling? If the problem persists can you open a bug with the details. Thanks.

**Comment by slazyk** [comment]
I updated the binary .zip in 'releases' to make it easier to update.
