### ISSUE TITLE
Adding a condition to an else

### ISSUE THREAD

**Issue by pip8786** [FuzzyAutocomplete/FuzzyAutocompletePlugin#62]
If I have an } else { at the end of a block of if/elses and I try to add an if to it so it becomes }else if(){ the autocomplete doesn't give me anything. I believe the old one would.

**Comment by slazyk** [comment]
Do I understand correctly that you want to autocomplete the `if()` upon typing `i` after `else `?
You can easily check what the old one would do by disabling the plugin in settings.
Does not autocomplete for me.

Also, while the plugin changes the scoring, it does not add nor remove any completions from the list of all the possibilities. Please reopen if that is actually what you are seeing, this indeed would be a bug.
