### ISSUE TITLE
can't use on xcode6.2

### ISSUE THREAD

**Issue by lazyjean** [FuzzyAutocomplete/FuzzyAutocompletePlugin#70]
the plugin didn't work on xcode6.2

**Comment by segiddins** [comment]
This is addressed already by https://github.com/FuzzyAutocomplete/FuzzyAutocompletePlugin/pull/66.

**Comment by slazyk** [comment]
That's correct. And I even put some text regarding this kind of issues into the readme...

Closing. Please reopen if the newest plugin version is affected.
