### ISSUE TITLE
not working in xcode 6.2

### ISSUE THREAD

**Issue by limbo-lab** [FuzzyAutocomplete/FuzzyAutocompletePlugin#71]
It does not work in my machine installed through alcatraz. But by downloading the latest .zip build, it works.

**Comment by wh1pch81n** [comment]
seems to be broken in 6.3 as well

**Comment by slazyk** [comment]
I just tried installing via Alcatraz (1.1.2) on both Xcode 6.2 and 6.3 and in both cases worked just fine.
Can you provide some more detail?

Which exact versions of Alcatraz, Xcode and OS X are you using?

Does Alcatraz output anything interesting/related while trying to install FuzzyAutocomplete?
You can filter by "Fuzzy" in Console.app.

Does Xcode output anything interesting/related when starting up?
You can filter by or "Fuzzy" in Console.app.

What exactly do you mean by "does not work"?
Is there a FuzzyAutocomplete menu item in Editor menu?
Can you access FuzzyAutocomplete settings from this menu?

**Comment by beoliveira** [comment]
Seems to be broken in *Xcode 6.3* with *Alcatraz 1.1.2*.
Doesn't show up in the Editor menu.

In the Console, filtering by "Fuzzy", I get this:
```
17/04/15 10:33:07,676 Xcode[41939]: Failed to load plugin at: /Users/bernardo/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```

Hope it helps.

**Comment by slazyk** [comment]
Thanks, that is exactly what I needed.

Can you check if you get the same error when you clone the project from github, open and build in Xcode manually?

**Comment by beoliveira** [comment]
Yeah, cloned it just now. The build fails in Xcode with this error:
```
/Users/bernardo/Documents/Projects/XcodePlugins/FuzzyAutocompletePlugin/FuzzyAutocomplete/FASettingsWindow.xib: The document "FASettingsWindow.xib" could not be opened. The operation couldn’t be completed. (com.apple.InterfaceBuilder error -1.)
```

**Comment by slazyk** [comment]
Looks a bug in ibtool or OS X, and specific to 10.10.3  (as springLoaded property was introduced then, and there is nothing in the XIB related to it). Are you running final version of 10.10.3 or some of the earlier developer previews?

Will try to reproduce on a 10.10.3 machine and figure out a workaround.

**Comment by slazyk** [comment]
Does not reproduce for me on Xcode 6.3 (6D570) and OS X 10.10.3 (14D131).

Are you able to open the xib in your version of Xcode?

Similarly to OS X, is your Xcode 6.3 final or one of the previews?
Do you have only one version of Xcode installed?
If more than one, does `xcode-select -p` print the path of the one you are expecting?

**Comment by wh1pch81n** [comment]
It was fine when I was on xcode 6.2 but when I upgraded, fuzzy  does not work. When typing there is no fuzzy auto completion.  There is no fuzzy in the menu.  But the Alcatraz says it is installed so I dunno.



—

**Comment by slazyk** [comment]
This hopefully is now obsolete
