### ISSUE TITLE
Doesn't autocomplete some deeply nested workspace headers

### ISSUE THREAD

**Issue by mulle-nat** [FuzzyAutocomplete/FuzzyAutocompletePlugin#73]
In my app A, I have a subproject B which is an umbrella framework. This in turns contains a subproject C which is another framework.

`#import <C`... doesn't autocomplete, yet Xcode picks the header up during compilation with no problem. There are no special search paths set.

**Comment by slazyk** [comment]
The plugin does not alter the full completion list, only they way it is filtered and presented.

Can you check if you get the completion you are expecting when you disable the plugin?
If not, the problem lies withis Xcode itself rather than the plugin (and there is not much we can do).

**Comment by mulle-nat** [comment]
Yes you are right, it's Xcodes problem really. Sorry for the false alert.

**Comment by slazyk** [comment]
What you can try is to delete DerivedData (iirc there should be an option to do this under Window > Organizer > Projects) and restart Xcode, wait for indexing to finish and see if it gets picked up then.
