### ISSUE TITLE
Not working on Xcode 6.3

### ISSUE THREAD

**Issue by mikeMTOL** [FuzzyAutocomplete/FuzzyAutocompletePlugin#74]
Plugin loads properly, but fuzzy matching not working.

**Comment by Ahti** [comment]
Same for me, the menu is usable, I can set settings and dis-/enable the plugin, but only the default Xcode completions are showing.

I am running Xcode 6.3 (6D570) on Yosemite 10.10.3 (14D131), and Installed FuzzyAutocomplete 2.1.0 via Alcatraz.

**Comment by slazyk** [comment]
Is it only the matching not working or the plugin in general.
E.g. does "Show List Header" setting have any effect?

Does it also happen if you install a [prebuild release from github](https://github.com/FuzzyAutocomplete/FuzzyAutocompletePlugin/releases)?

**Comment by robertjpayne** [comment]
@slazyk looks like the info.plist needs updating with new compatibility uuids

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>63FC1C47-140D-42B0-BB4D-A10B2D225574</string>
	<string>37B30044-3B14-46BA-ABAA-F01000C27B63</string>
	<string>640F884E-CE55-4B40-87C0-8869546CAB7A</string>
	<string>A2E4D43F-41F4-4FB9-BB94-7177011C9AED</string>
	<string>AD68E85B-441B-4301-B564-A45E4919A6AD</string>
	<string>C4A681B0-4A26-480E-93EC-1218098B9AA0</string>
	<string>FEC992CC-CA4A-4CFD-8881-77300FCB848A</string>
	<string>992275C1-432A-4CF7-B659-D84ED6D42D3F</string>
	<string>A16FF353-8441-459E-A50C-B071F53F51B7</string>
	<string>9F75337B-21B4-4ADC-B558-F9CADF7073A7</string>
	<string>992275C1-432A-4CF7-B659-D84ED6D42D3F</string>
	<string>8DC44374-2B35-4C57-A6FE-2AD66A36AAD9</string>
	<string>E969541F-E6F9-4D25-8158-72DC3545A6C6</string>
</array>
</plist>
```

**Comment by mritrifork** [comment]
I had the same problem and did as @robertjpayne  suggested, and added the new key to F

**Comment by mritrifork** [comment]
I had the same problem and did as @robertjpayne suggested, and added the new key to FuzzyAutocomplete/FuzzyAutocomplete-Info.plist, rebuild the project (`/usr/bin/xcodebuild -project FuzzyAutocomplete.xcodeproj`) and restarted xcode and it worked. 

By the way, the new CompatibilityUUID can be read out of xcode using the following command.
`defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`

**Comment by slazyk** [comment]
Original issue here is not related to `DVTPlugInCompatibilityUUID` as the plugin reportedly loads

**Comment by rfsbsb** [comment]
Just to report it's not working on Xcode 6.4, on OSX 10.10.4 installed via Alcatraz.

When I open Alcatraz it says the plugin is installed but it doesn't show on menu nor it auto complete anything. If I go to Alcatraz, remove and install again the plugin, it work again. But if I close Xcode and open again, the behavior repeats.

When I run:

    defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4

This is the result:
```
{
    allowed =     {
        "com.flexih.CComment" =         {
            version = 1;
        };
        "com.kinwah.XcodeRefactoringPlus" =         {
            version = 1;
        };
        "com.luisfloreani.Auto-Importer" =         {
            version = 1;
        };
        "com.mneorr.Alcatraz" =         {
            version = 1;
        };
        "me.delisa.CocoaPods" =         {
            version = 1;
        };
        "org.vu0.BBUDebuggerTuckAway" =         {
            version = 1;
        };
    };
    skipped =     {
        "com.github.xlc.XLCXcodeAssist" =         {
            version = "1.0";
        };
        "com.markohlebar.Peckham" =         {
            version = 1;
        };
        "com.omz-software.OMColorSense" =         {
            version = "1.0.1";
        };
        "com.omz-software.OMQuickHelp" =         {
            version = "1.0.1";
        };
        "com.plumn.XToDo" =         {
            version = 1;
        };
        "com.pragmaticcode.UncrustifyPlugin" =         {
            version = "2.1.1";
        };
        "com.tendencystudio.AMMethod2Implement" =         {
            version = "3.1";
        };
        "com.travisjeffery.ClangFormat" =         {
            version = 1;
        };
        "io.github.FuzzyAutocomplete" =         {
            version = "2.1.0";
        };
        "org.vu0.BBUFullIssueNavigator" =         {
            version = 1;
        };
    };
}
```

Let me know if you need anything else.

**Comment by zolivier** [comment]
@rfsbsb 
- Close Xcode
- Open a terminal and run: `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4`
- Re-open Xcode and make sure you select 'Load Bundles'. That should whitelist at least FuzzyAutocomplete.

**Comment by slazyk** [comment]
This hopefully is now obsolete
