### ISSUE TITLE
Code completion no longer works after extensive use

### ISSUE THREAD

**Issue by gdavis** [FuzzyAutocomplete/FuzzyAutocompletePlugin#79]
I've been working in my first Swift app for the last couple weeks, and I keep noticing that FuzzyAutocomplete will stop working after a few hours of working in the IDE. In order to get the plugin working again I have to uninstall then reinstall. I'm using Alcatraz, Xcode 6.3.2, and this happens several times a day. Any thoughts?

**Comment by slazyk** [comment]
You have to uninstall and reinstall, meaning restarting Xcode does not help?

How does it stop working? Stops showing completions? Are you able to enter the settings?

When it happens, can you look in Console.app for anything related to Xcode or Fuzzy?

**Comment by gdavis** [comment]
Restarting does not seem to help. It stops working by reverting back to the standard Xcode auto-completion. It stops being "fuzzy". 

I'm not sure what you mean by entering the settings? Next time this happens, I'll see if I can find anything in Console.app related to the plugin.

**Comment by slazyk** [comment]
That is very interesting. Do you see any other weird Xcode behavior?

Anything in the logs related to Xcode, SourceKit or FuzzyAutocomplete will be helpful.

By entering the settings I mean Editor > FuzzyAutocomplete > Plugin Settings menu item.

**Comment by gdavis** [comment]
I can indeed open the Plugin Settings just fine. I haven't really seen any weird behavior other than this, and its the only plugin I have enabled. 

I'll be sure to post anything I find in the logs today.

**Comment by gdavis** [comment]
Okay, it happened and I captured some logs that look promising. [You can find the Gist here](a7f881910cf2bc74f618).

What sticks out to me is this: 
![image](https://cloud.githubusercontent.com/assets/110691/8072550/9a3d813c-0ed4-11e5-8511-096b106ffff3.png)

**Comment by gdavis** [comment]
I also double-checked and it does indeed take a reinstall of the plugin to get fuzzy autocomplete working again. Restarting Xcode alone did not fix the issue.

**Comment by gdavis** [comment]
Any insight into this? Its still happening several times a day for me, both in ObjC and Swift.

**Comment by grzegorzdvipek** [comment]
+1 I have the same issue on XCode 6.3.2 (6D2105) and FuzzyAutocomplete 2.1. Additionally, I can confirm that previous versions of Fuzzy also don't work... Both Obj-C and Swift.

**Comment by heps** [comment]
+1 - the same issue - XCode 6.3.2, FuzzyAutocomplete 2.1

**Comment by slazyk** [comment]
Is this still reproducible? The issue gdavis mentioned was fixed in 2.1.1.

**Comment by gdavis** [comment]
Haven’t seen this happen in a while. Currently using 2.1.1. 👍🏻
