### ISSUE TITLE
keyboard shortcuts for highlighting next/previous seem reversed.

### ISSUE THREAD

**Issue by Rivukis** [FuzzyAutocomplete/FuzzyAutocompletePlugin#80]
This is more of a preference issue, but generally on a mac keyboard if a there is a shortcut for "next thing" and "previous thing" then the keyboard shortcut for "previous thing" is usually the same as the keyboard shortcut for "next thing" plus the shift key  (i.e. TAB = next highlighted argument && SHIFT+TAB = previous highlighted argument, COMMAND+APOSTROPHE = next issue, COMMAND+SHIFT+APOSTROPHE = previous issue, etc.).

So, I feel like it would make more sense for the command for "next item in list" should be CONTROL+PERIOD and the previous item in the list should be CONTROL+SHIFT+PERIOD. Right now the opposite is true.

**Comment by slazyk** [comment]
Thanks for noticing. Indeed somehow I managed to explicitly make it work the other way than what Xcode is doing by default.
