### ISSUE TITLE
The same bug as in autocomplete

### ISSUE THREAD

**Issue by gerchicov-bp** [FuzzyAutocomplete/FuzzyAutocompletePlugin#82]
I can understand if you can't fix it but anyways...
If you write a property and want to set its ```getter``` or ```setter``` then xCode suggests a list of methods and all of them are usually incorrect. Your plugin doesn't suggest a correct list too. But in this case the standard behaviour is even better than your one because in this case it at least allows to see the exact keyboard output and your plugin always tries to replace the current word with another one from list.

I could suggest one of the following solutions:
- to disable your pugin for setting of getter/setter params;
- to show a really complete list of word comletions. Note: a programmer can set any method as setter/getter even if this method is private for current object (doesn't exist in the current .h file but is declared in .m file)

**Comment by slazyk** [comment]
FYI the plugin already allows for seeing exact keyboard output in two ways:

- if you enable "list header" in the plugin options
- if you disable "inline preview" in the plugin options (or "type over completions" in Xcode options)

Also, there are several options allowing you to tweak the SNR of completions to your liking, e.g.:

- you can filter completions by score more aggressively
- you can choose to require at least a few letters to be the prefix of the match
- you can tweak the scoring function to your liking

The plugin is context independent. It neither removes nor adds any completions to the list that Xcode generates for given context.
