### ISSUE TITLE
Fuzzy Autocomplete via Alcatraz in Xcode7-beta not working.

### ISSUE THREAD

**Issue by orkenstein** [FuzzyAutocomplete/FuzzyAutocompletePlugin#85]
Hi! 
In Xcode7-beta Fuzzy plugin installed vie Alcatraz does not work.

**Comment by st2340596** [comment]
Xcode7-beta4  uzzy plugin installed vie Alcatraz does not work...

**Comment by orkenstein** [comment]
@st2340596 
You can clone project manually and build from **xcode7** branch.
