### ISSUE TITLE
Slows typing to a crawl in 7.0.1

### ISSUE THREAD

**Issue by philosopherdog** [FuzzyAutocomplete/FuzzyAutocompletePlugin#95]
Totally slows down typing. I'm on a retina with ssd. So, plenty of power. Turning off the plugin solves the slow down. But I love this plugin!

**Comment by philosopherdog** [comment]
Ok, I solved it with a manual install. I had it installed through the package manager.

**Comment by slazyk** [comment]
Do you mean that version from Alcatraz was substantially slower than one built manually?

**Comment by philosopherdog** [comment]
For me it was.
