### ISSUE TITLE
Please give support for Xcode 7.1

### ISSUE THREAD

**Issue by hardikdevios** [FuzzyAutocomplete/FuzzyAutocompletePlugin#98]
Plugin not working in latest Xcode 7.1 which is now officially released.

**Comment by ndonald2** [comment]
:+1:

**Comment by keith** [comment]
This can be closed for https://github.com/FuzzyAutocomplete/FuzzyAutocompletePlugin/pull/96 and https://github.com/FuzzyAutocomplete/FuzzyAutocompletePlugin/pull/97
